### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by yusurko** [i-net-software/dokuwiki-plugin-dw2markdown#1]
Link in README file points to `github.org` instead of `github.com`

**Comment by gamma** [comment]
Fixed

**Comment by AzureCloudMonk** [comment]
Hi, Is this plugin working? I don't see Docs for it on the link you specify or over at DokuWiki.org. Looks interesting. I installed it but don't see a user interface for it or any changes listed for config in the DokuWiki Configuration Manager.

Thanks for your work.

**Comment by gamma** [comment]
It does, even though in a simplified way. It is just a renderer, so you have to call it using `?do=export_dw2markdown`. There is no additional configuration.
