### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by gianlucavagnuzzi** [i-net-software/dokuwiki-plugin-dw2markdown#2]
hi!
i've installed successfully but i don't see selectable in renderer_xhtml option of dokuwiki administration menu.
can you helpme?

**Comment by damufo** [comment]
Same problem.
How to make it render on markdown?

**Comment by gamma** [comment]
Hi, the dw2markdown renderer is not suited for XHMTL output and does not support it. That is is why it is not available in the configuration.

You can use it to export single pages into markdown, e.g. using the siteexport plugin. To use it manually you would do `do=export_dw2markdown` to your URL. Even then it will only work with simple language features.

**Comment by damufo** [comment]
Sorry for asking this here.
With this plugin, is it possible to write markdown documents to dokuwiki by default?
Can't find how?
Please visit this page https://jacksonraila.wordpress.com/2021/02/28/plain-text-file-markdown-wiki-is-not-a-thing/
